---
title: "Teaching"
---

## Student advising as (co-)chair 
* University of Maryland, College Park
  + Full, empirical qualifying papers 
      + Woodward, Jill
      + Simmons, Stefaine
      + Tytko, Tetiana (completed)
      
  + Proposal qualifying papers
      + Hersh, Meghan
      + Jia, Ruirui (completed)
      + Ogawa, Sanshiro (completed)
      + Park, Sohye (completed)
      + Ryu, Hyeran 
      + Tytko, Tetiana (completed)
      + Wu, Zhiyi (completed)
    
  + Dissertations 
    + Deng, Zhiyuan^3,4^ (co-chair with Kira Gor; completed)
    + Iizuka, Takehiro^1,3,4^ (completed)
    + Jia, Ruirui 
    + Malone, Jon^1,2,4^ (co-chair with Kira Gor, completed)
    + Park, Sohye (co-chair with Ekaterina Sudina)
    + Pulupa, Catherine (completed)
    + Tytko, Tetiana^5^
    
    *Notes*: ^1^recipient of the *Language Learning* Dissertation Grant; ^2^recipient of the TIRF Doctoral Dissertation Grant; ^3^recipient of the TOEFL Grant for Doctoral Research in Language Assessment; ^4^recipient of the Duolingo Doctoral Dissertation Award; ^5^recipient of the NFMLTA/MLJ Dissertation Writing Support Grant
    
## Graduate-level courses

* University of Maryland, College Park

  + *SLAA 620 Second Language Research Methodologies* Fall, 2023; Fall 2024
  + *SLAA 640 Psycholinguistics* Fall, 2022
  + *SLAA 649R Research Critique in Second Language Acquisition* Spring, 2023; Fall 2024
  + *SLAA 479T Advanced Statistics for Second Language Research* Spring 2025
  + *SLAA 750 Instructed Second Language Acquisition* Fall, 2022; Fall, 2023
  + *SLAA 759L Vocabulary Acquisition in Instructional Contexts* Spring, 2023; Spring 2025 

* Michigan State University

  +  *LLT 873 Quantitative Research Methods in SLS* (co-teaching with Prof. Shawn Loewen) Fall, 2019

## Undergraduate-level courses

* Michigan State University

  +  *LLT 346 Pedagogical Grammar* Spring, 2020

## Sub-degree level course

* Caritas Institute of Higher Education (Hong Kong)

  +  *ENG 102 Use of English* Semester 2, 2015/6

## Secondary school (Middle & High school)

* SKH St Simon’s Lui Ming Choi Secondary School

  +  Secondary 1-6 (Grades/Years 7-12) EFL 2013-2017

* Fanling Kau Yan College

  +  Secondary 1-6 (Grades/Years 7-12) EFL 2009-2012
  
## Workshops Taught
  * [Pay-It-Forward charity workshop in R](https://bronson-hui.github.io/payitforwardworkshops/index.html). Two-day online workshop, July-August, 2021. (with Ma, W.Y.M., Huntley, E., and Yoder, M.)
  * An overview of reliability measures. Center for Statistical Training and Consulting (CSTAT), Michigan State University, March, 2021.(with Ma, W.Y.M.)
  * Graduate students’ perspectives on open science practices. Center for Statistical Training and Consulting (CSTAT), Michigan State University, November, 2020.(with Huntley, E.)
  *  Online data collection for psycholinguistics research: an introduction. Coffee and Cognition (psycholinguistics reading group), Second Language Studies, Michigan State University, October, 2020. (with Huntley, E.)
  * Analyzing eye-tracking data. [a series of workshops]. Department of Language and Linguistics, University of Essex, September, 2020. 
  * Data management and sharing in L2 research: why and how [a two-hour workshop]. Donuts and Distribution (Quant methods reading group), Second Language Studies, Michigan State University, February, 2020. (with Calvert, S.)
  * Multilevel (mixed-effects) modelling using R [a three-hour workshop]. Social Science Data Analytics, Michigan State University, November, 2019.
  * Introduction to R [a one-hour workshop]. Donuts and Distribution (Quant methods reading group), Second Language Studies, Michigan State University, October, 2018.
  * Introduction to R [a series of one-hour workshops]. Second Language Studies, Michigan State University, April–July, 2018. 
